Repository UKHomeOffice/asl-components, pull requests merged in 2024-02, with the labels that each got.

#323 [ASL-4380] Markdown fixes to display nested lists
  package-lock.json
  package.json
  src/conditions/index.jsx
  src/markdown/index.jsx
  src/snippet/index.spec.jsx
Labels: major

#324 ASL-4474 - Provide context for templates in fieldset and model summary snippets
  package.json
  src/fieldset/index.jsx
  src/model-summary/index.jsx
Labels: minor

#325 [ASL-4474] Model Summary - Recursively show revealled properties
  package.json
  src/model-summary/index.jsx
Labels: minor

#326 Update dependency asl-constants from 2.0.0 to 2.1.4
  package-lock.json
  package.json
Labels: dependencies, patch
